name: HTML Proofer

on:
  push:
    branches:
      - feature/html-proofer-action # to be able to test this PR

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.4' # To use version matching the one of actions/jekyll-build-pages@v1.0.5
          bundler-cache: true
      - uses: actions/jekyll-build-pages@v1.0.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          bundle exec htmlproofer --checks Links --disable-external=true \
            --enforce-https=false _site/
