name: HTML Proofer

on:
  push:
    branches:
      - feature/html-proofer-action # to be able to test this PR

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: actions/jekyll-build-pages@v1.0.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          bundle exec htmlproofer --assume-extension .html --disable-external=true \
            --enforce-https=false _site/
        env:
          NUMBER: ${{ github.event.issue.number }}
