name: HTML Proofer

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run html-proofer on'
        required: true
        default: 'master'

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.4' # To use version matching the one of actions/jekyll-build-pages@v1.0.5
          bundler-cache: true
      - uses: actions/jekyll-build-pages@v1.0.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          bundle exec htmlproofer --assume-extension .html --disable-external=true \
            --checks Links --enforce-https=false _site/
